#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Abre una carpeta seleccionada de la lista
##?
##? Usage:
##?    open_common
docs::parse "$@"

declare -A folders

folders=(
	["🔗 Codely"]="https://codely.com"
	["🔗 Pro"]="https://pro.codely.com"
	["📁 Downloads"]="$HOME/Downloads"
	["📁 Desktop"]="$HOME/Desktop"
)

folder=$(printf "%s\n" "${!folders[@]}" | choose)

if [[ -n ${folders[$folder]} ]]; then
    open "${folders[$folder]}"
else
    echo "No folder selected"
fi