#!/usr/bin/env bash

declare -A commands

commands=(
	["domain"]="faker-cli --internet domainName"
	["email"]="faker-cli --internet email"
	["name"]="faker-cli --names firstName"
	["uuid"]="uuidgen"
)

command=$(printf "%s\n" "${!commands[@]}" | choose)

if [[ -n ${commands[$command]} ]]; then
    eval "${commands[$command]}" | sed 's/"//g' | pbcopy
else
    echo "No command selected"
fi