#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Prueba de rendimiento de arranque de ZSH
##?
##? Usage:
##?   zsh_test_performance
docs::parse "$@"	

for i in $(seq 1 10); do /usr/bin/time /bin/zsh -i -c exit; done